import Bot from "../models/bot.model.js";
import User from "../models/user.model.js";

export const Message=async(req,res)=>{
    try{
        const{text}=req.body;
        console.log(text);
        if(!text?.trim()){
            return res.status(400).json({error:"Text cannot be empty"});
        }

        const user=await User.create({
            sender:'user',
            text
        })

    //Data
    const botResponses={
      "hi": { "answer": "Hello! How are you?" },
      "hello": { "answer": "Hi, How can I help you?" },
      "hey": { "answer": "Hey there! What’s up?" },
      "good morning": { "answer": "Good morning! Have a great day ahead." },
      "good night": { "answer": "Good night! Sleep well." },
      "thank you": { "answer": "You’re welcome!" },
      "bye": { "answer": "Goodbye! Take care." },
      "how are you": { "answer": "I’m doing great, thank you! How about you?" },
      "what is your name": { "answer": "I’m ChatBot, your AI assistant." },
      "who made you": { "answer": "I was created by developers to help people with answers." },
      "what can you do": { "answer": "I can answer questions, chat with you, and share knowledge." },
      "i love you": { "answer": "That’s sweet! I’m here to help you always." },
      "where are you from": { "answer": "I live in the cloud — no rent, no bills!" },
      "tell me a joke": { "answer": "Why don’t skeletons fight? They don’t have the guts!" },
      "what is sql": { "answer": "SQL stands for Structured Query Language, used to interact with databases." },
      "what is python": { "answer": "Python is a high-level, easy-to-learn programming language used in many fields." },
      "what is java": { "answer": "Java is an object-oriented programming language known for portability." },
      "what is javascript": { "answer": "JavaScript is the language of the web, enabling interactivity in websites." },
      "what is html": { "answer": "HTML is the standard markup language for creating web pages." },
      "what is css": { "answer": "CSS is used to style and design HTML pages." },
      "what is database": { "answer": "A database is an organized collection of structured information or data." },
      "what is recursion": { "answer": "Recursion is when a function calls itself until a base condition is met." },
      "what is operating system": { "answer": "An OS is system software that manages hardware and software resources." },
      "who is prime minister of india": { "answer": "Narendra Modi is the Prime Minister of India." },
      "who is president of india": { "answer": "Droupadi Murmu is the President of India since 2022." },
      "what is g20": { "answer": "The G20 is a group of 19 countries plus the EU that discusses global economic issues." },
      "tell me about yourself": { "answer": "I am ChatBot, designed to chat and share information." },
      "why should we hire you": { "answer": "Because I bring useful skills, knowledge, and enthusiasm." },
      "what is leadership": { "answer": "Leadership is the ability to guide and inspire people to achieve goals." },
      "strengths and weaknesses": { "answer": "Strengths: problem-solving, adaptability. Weaknesses: perfectionism, public speaking." },
      "who is virat kohli": { "answer": "Virat Kohli is a famous Indian cricketer and former team captain." },
      "what is ipl": { "answer": "The IPL is India’s professional Twenty20 cricket league." },
      "current affairs": { "answer": "Recent events include India’s G20 summit and Chandrayaan-3 mission." },
      "what is ai": { "answer": "Artificial Intelligence is the simulation of human intelligence in machines." },
      "what is machine learning": { "answer": "ML is a subset of AI that enables systems to learn from data automatically." },
      "what is deep learning": { "answer": "Deep Learning is a subset of ML using neural networks with multiple layers." },
      "what is data science": { "answer": "Data Science is the study of data to extract useful insights." },
      "what is cloud computing": { "answer": "Cloud computing provides services like storage and computing power over the internet." },
      "what is devops": { "answer": "DevOps is a set of practices combining software development and IT operations." },
      "what is blockchain": { "answer": "Blockchain is a decentralized, distributed digital ledger for transactions." },
      "what is cryptocurrency": { "answer": "Cryptocurrency is digital money secured by cryptography, like Bitcoin." },
      "what is big data": { "answer": "Big Data refers to extremely large datasets analyzed for insights." },
      "what is iot": { "answer": "IoT means Internet of Things — connecting devices to the internet." },
      "what is 5g": { "answer": "5G is the fifth generation of mobile networks, offering faster speed and connectivity." },
      "what is robotics": { "answer": "Robotics is the field of designing and creating robots." },
      "what is ar": { "answer": "Augmented Reality overlays digital content onto the real world." },
      "what is vr": { "answer": "Virtual Reality immerses users in a completely digital environment." },
      "what is metaverse": { "answer": "The Metaverse is a virtual shared world accessed via the internet." },
      "what is github": { "answer": "GitHub is a platform for hosting and collaborating on code repositories." },
      "what is git": { "answer": "Git is a version control system to manage code history and collaboration." },
      "what is docker": { "answer": "Docker is a platform to build and run applications in containers." },
      "what is kubernetes": { "answer": "Kubernetes is a container orchestration system for managing applications." },
      "what is api": { "answer": "API stands for Application Programming Interface, a way for apps to talk to each other." },
      "what is rest api": { "answer": "A REST API uses HTTP methods to interact with resources." },
      "what is graphql": { "answer": "GraphQL is a query language for APIs that allows clients to request specific data." },
      "what is json": { "answer": "JSON stands for JavaScript Object Notation, a lightweight data format." },
      "what is xml": { "answer": "XML is a markup language for storing and transporting data." },
      "what is front end": { "answer": "Frontend development is about building the user interface of a website or app." },
      "what is backend": { "answer": "Backend development handles data processing and server logic." },
      "what is full stack": { "answer": "Full Stack development combines both frontend and backend skills." },
      "what is react": { "answer": "React is a popular JavaScript library for building UIs." },
      "what is angular": { "answer": "Angular is a TypeScript-based web development framework." },
      "what is vue": { "answer": "Vue.js is a lightweight JavaScript framework for building UIs." },
      "what is nodejs": { "answer": "Node.js is a JavaScript runtime for building backend applications." },
      "what is express": { "answer": "Express is a minimal Node.js framework for building web apps and APIs." },
      "what is mongodb": { "answer": "MongoDB is a NoSQL database storing data in JSON-like documents." },
      "what is mysql": { "answer": "MySQL is a relational database management system." },
      "what is postgresql": { "answer": "PostgreSQL is an advanced open-source relational database." },
      "what is oracle db": { "answer": "Oracle Database is a relational database system used by enterprises." },
      "what is firebase": { "answer": "Firebase is a Google platform for building and scaling web/mobile apps." },
      "what is aws": { "answer": "Amazon Web Services is a cloud computing platform." },
      "what is azure": { "answer": "Microsoft Azure is a cloud computing service platform." },
      "what is google cloud": { "answer": "Google Cloud provides cloud services including storage and AI." },
      "what is cyber security": { "answer": "Cybersecurity is the practice of protecting systems from digital attacks." },
      "what is hacking": { "answer": "Hacking is unauthorized access to computer systems or data." },
      "what is ethical hacking": { "answer": "Ethical hacking is testing systems for vulnerabilities legally." },
      "what is bug bounty": { "answer": "Bug bounty is a reward program for finding and reporting bugs." },
      "what is testing": { "answer": "Software testing ensures software works as expected without bugs." },
      "what is unit testing": { "answer": "Unit testing checks individual parts of code for correctness." },
      "what is integration testing": { "answer": "Integration testing checks how components work together." },
      "what is system testing": { "answer": "System testing validates the entire application as a whole." },
      "what is regression testing": { "answer": "Regression testing ensures changes don’t break existing features." },
      "what is manual testing": { "answer": "Manual testing is checking software manually without automation." },
      "what is automation testing": { "answer": "Automation testing uses scripts and tools to test software." },
      "what is selenium": { "answer": "Selenium is a popular tool for browser automation testing." },
      "what is jira": { "answer": "Jira is a project management and bug tracking tool." },
      "what is agile": { "answer": "Agile is a project management approach emphasizing flexibility and iteration." },
      "what is scrum": { "answer": "Scrum is an Agile framework with roles, events, and artifacts." },
      "what is sprint": { "answer": "A sprint is a fixed time period to complete specific work in Agile." },
      "what is kanban": { "answer": "Kanban is a visual method for managing workflow using boards." },
      "what is waterfall model": { "answer": "Waterfall is a sequential software development model." },
      "what is software engineering": { "answer": "Software engineering is the disciplined approach to building software." },
      "what is dsa": { "answer": "DSA stands for Data Structures and Algorithms, core of programming." },
      "what is array": { "answer": "An array is a data structure that stores elements in contiguous memory." },
      "what is linked list": { "answer": "A linked list is a data structure where each element points to the next." },
      "what is stack": { "answer": "A stack is a LIFO (Last In, First Out) data structure." },
      "what is queue": { "answer": "A queue is a FIFO (First In, First Out) data structure." },
      "what is tree": { "answer": "A tree is a hierarchical data structure with nodes and edges." },
      "what is graph": { "answer": "A graph is a data structure with nodes and edges, directed or undirected." },
      "what is bst": { "answer": "A Binary Search Tree is a tree where left child < parent < right child." },
  "what is hash table": { "answer": "A hash table stores key-value pairs using a hash function." },
  "what is heap": { "answer": "A heap is a complete binary tree used in priority queues." },
  "what is binary tree": { "answer": "A binary tree is a tree where each node has at most two children." },
  "what is sorting": { "answer": "Sorting arranges data in ascending or descending order." },
  "what is searching": { "answer": "Searching finds an element in a dataset." },
  "what is linear search": { "answer": "Linear search checks each element one by one." },
  "what is binary search": { "answer": "Binary search finds elements by dividing the search space in half." },
  "what is quicksort": { "answer": "QuickSort is a divide-and-conquer sorting algorithm." },
  "what is mergesort": { "answer": "MergeSort divides arrays into halves and merges them in sorted order." },
  "what is bubble sort": { "answer": "Bubble Sort repeatedly swaps adjacent elements if they are in wrong order." },
  "what is selection sort": { "answer": "Selection Sort repeatedly selects the smallest element and places it at the start." },
  "what is insertion sort": { "answer": "Insertion Sort builds a sorted array one item at a time." },
  "what is dynamic programming": { "answer": "DP is solving problems by breaking them into overlapping subproblems." },
  "what is greedy algorithm": { "answer": "Greedy algorithms make locally optimal choices to find a global optimum." },
  "what is graph traversal": { "answer": "Graph traversal means visiting all nodes (DFS or BFS)." },
  "what is bfs": { "answer": "Breadth-First Search explores nodes level by level." },
  "what is dfs": { "answer": "Depth-First Search explores as far as possible along each branch." },
  "what is compiler": { "answer": "A compiler translates source code into machine code." },
  "what is interpreter": { "answer": "An interpreter executes code line by line." },
  "what is assembler": { "answer": "An assembler converts assembly code into machine code." },
  "what is ide": { "answer": "An IDE is an Integrated Development Environment for coding." },
  "what is sdk": { "answer": "A Software Development Kit is a collection of tools and libraries." },
  "what is framework": { "answer": "A framework provides structure and tools for building software." },
  "what is library": { "answer": "A library is a collection of reusable code modules." },
  "what is algorithm": { "answer": "An algorithm is a step-by-step process to solve a problem." },
  "what is pseudo code": { "answer": "Pseudo code is a plain-language representation of an algorithm." },
  "what is flowchart": { "answer": "A flowchart is a visual diagram showing process steps." },
  "what is oop": { "answer": "Object-Oriented Programming organizes code into objects with properties and methods." },
  "what is class": { "answer": "A class is a blueprint for creating objects." },
  "what is object": { "answer": "An object is an instance of a class." },
  "what is inheritance": { "answer": "Inheritance allows one class to derive properties from another." },
  "what is polymorphism": { "answer": "Polymorphism allows methods to take many forms." },
  "what is encapsulation": { "answer": "Encapsulation hides internal details of a class from outside." },
  "what is abstraction": { "answer": "Abstraction shows essential features while hiding details." },
  "what is constructor": { "answer": "A constructor initializes an object when it is created." },
  "what is destructor": { "answer": "A destructor frees resources when an object is destroyed." },
  "what is interface": { "answer": "An interface defines a contract that classes must follow." },
  "what is exception": { "answer": "An exception is an error that disrupts normal program flow." },
  "what is exception handling": { "answer": "Exception handling manages runtime errors gracefully." },
  "what is multithreading": { "answer": "Multithreading allows multiple threads to run concurrently." },
  "what is deadlock": { "answer": "Deadlock is when two or more processes are waiting forever for resources." },
  "what is semaphore": { "answer": "A semaphore is used to control access to shared resources in concurrency." },
  "what is process": { "answer": "A process is a running instance of a program." },
  "what is thread": { "answer": "A thread is a lightweight process within a process." },
  "what is scheduling": { "answer": "Scheduling decides which process runs at a given time." },
  "what is cpu scheduling": { "answer": "CPU scheduling selects which process gets CPU next." },
  "what is fcfs": { "answer": "First-Come, First-Served is a scheduling algorithm." },
  "what is sjf": { "answer": "Shortest Job First is a scheduling algorithm." },
  "what is round robin": { "answer": "Round Robin scheduling gives each process a time slice." },
  "what is priority scheduling": { "answer": "Priority scheduling gives CPU to highest-priority processes." },
  "what is paging": { "answer": "Paging is a memory management scheme dividing memory into pages." },
  "what is segmentation": { "answer": "Segmentation divides memory into variable-sized segments." },
  "what is cache": { "answer": "Cache is fast memory storing frequently used data." },
  "what is virtual memory": { "answer": "Virtual memory allows using disk as an extension of RAM." },
  "what is file system": { "answer": "A file system organizes and stores files on storage devices." },
  "what is database normalization": { "answer": "Normalization organizes data to reduce redundancy." },
  "what is 1nf": { "answer": "First Normal Form removes duplicate columns." },
  "what is 2nf": { "answer": "Second Normal Form removes partial dependencies." },
  "what is 3nf": { "answer": "Third Normal Form removes transitive dependencies." },
  "what is primary key": { "answer": "A primary key uniquely identifies a record in a table." },
  "what is foreign key": { "answer": "A foreign key links two tables together." },
  "what is unique key": { "answer": "A unique key ensures all values in a column are distinct." },
  "what is composite key": { "answer": "A composite key uses multiple columns to uniquely identify a record." },
  "what is index": { "answer": "An index improves database query performance." },
  "what is view": { "answer": "A view is a virtual table based on SQL queries." },
  "what is stored procedure": { "answer": "A stored procedure is a set of SQL statements stored in the database." },
  "what is trigger": { "answer": "A trigger automatically executes in response to events." },
  "what is cursor": { "answer": "A cursor is used to iterate over query results in databases." },
  "what is join": { "answer": "A join combines rows from two or more tables." },
  "what is inner join": { "answer": "Inner join returns rows with matching values in both tables." },
  "what is left join": { "answer": "Left join returns all rows from the left table, and matches from the right." },
  "what is right join": { "answer": "Right join returns all rows from the right table, and matches from the left." },
  "what is full join": { "answer": "Full join returns all rows when there is a match in either table." },
  "what is self join": { "answer": "Self join joins a table with itself." },
  "what is cross join": { "answer": "Cross join returns the Cartesian product of two tables." },
  "what is sql injection": { "answer": "SQL injection is a security vulnerability that manipulates queries." },
  "what is normalization vs denormalization": { "answer": "Normalization reduces redundancy, denormalization increases speed." },
  "what is cloud computing service models": { "answer": "IaaS, PaaS, SaaS are the main cloud service models." },
  "what is iaas": { "answer": "Infrastructure as a Service provides virtualized computing resources." },
  "what is paas": { "answer": "Platform as a Service provides a platform for app development." },
  "what is saas": { "answer": "Software as a Service delivers apps over the internet." },
  "what is computer network": { "answer": "A network is a collection of computers connected to share resources." },
  "what is lan": { "answer": "LAN is a Local Area Network connecting devices in a small area." },
  "what is wan": { "answer": "WAN is a Wide Area Network covering large areas like countries." },
  "what is man": { "answer": "MAN is a Metropolitan Area Network covering cities." },
  "what is tcp ip": { "answer": "TCP/IP is a suite of communication protocols for the internet." },
  "what is udp": { "answer": "UDP is a fast, connectionless protocol with no delivery guarantees." },
  "what is dns": { "answer": "DNS translates domain names into IP addresses." },
  "what is http": { "answer": "HTTP is the Hypertext Transfer Protocol for web communication." },
  "what is https": { "answer": "HTTPS is HTTP with encryption (SSL/TLS)." },
  "what is ftp": { "answer": "FTP is File Transfer Protocol to transfer files between computers." },
  "what is smtp": { "answer": "SMTP is Simple Mail Transfer Protocol for sending emails." },
  "what is pop3": { "answer": "POP3 is Post Office Protocol for retrieving emails." },
  "what is imap": { "answer": "IMAP is Internet Message Access Protocol for accessing emails." },
  "what is firewall": { "answer": "A firewall monitors and controls incoming/outgoing network traffic." },
  "what is vpn": { "answer": "A VPN creates a secure connection over the internet." },
  "what is ip address": { "answer": "An IP address identifies a device on a network." },
  "what is ipv4": { "answer": "IPv4 is the 4th version of Internet Protocol using 32-bit addresses." },
  "what is ipv6": { "answer": "IPv6 is the 6th version of Internet Protocol using 128-bit addresses." },
  "what is mac address": { "answer": "A MAC address uniquely identifies a network interface card." },
  "what is osi model": { "answer": "The OSI model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application." },
  "what is physical layer": { "answer": "The physical layer transmits raw bits over physical media." },
  "what is data link layer": { "answer": "The data link layer handles error detection and framing." },
  "what is network layer": { "answer": "The network layer is responsible for routing and addressing." },
  "what is transport layer": { "answer": "The transport layer ensures reliable delivery of data." },
  "what is session layer": { "answer": "The session layer manages sessions between applications." },
  "what is presentation layer": { "answer": "The presentation layer translates data formats (encryption, compression)." },
  "what is application layer": { "answer": "The application layer provides services like email, web browsing, file transfer." },
  "what is bandwidth": { "answer": "Bandwidth is the maximum rate of data transfer in a network." },
  "what is latency": { "answer": "Latency is the time taken for data to travel from source to destination." },
  "what is throughput": { "answer": "Throughput is the actual rate of successful data transfer." },
  "what is packet": { "answer": "A packet is a unit of data transmitted over a network." },
  "what is routing": { "answer": "Routing is selecting paths to send network traffic." },
  "what is switching": { "answer": "Switching forwards data packets within a network." },
  "what is hub": { "answer": "A hub is a basic networking device that broadcasts data to all devices." },
  "what is switch": { "answer": "A switch forwards data to the specific destination device using MAC addresses." },
  "what is router": { "answer": "A router connects different networks and directs traffic." },
  "what is gateway": { "answer": "A gateway connects networks using different protocols." },
  "what is proxy server": { "answer": "A proxy server acts as an intermediary between client and server." },
  "what is load balancer": { "answer": "A load balancer distributes traffic across multiple servers." },
  "what is dos attack": { "answer": "Denial of Service attack overwhelms a system to make it unavailable." },
  "what is ddos attack": { "answer": "Distributed Denial of Service attack uses multiple machines to flood a target." },
  "what is phishing": { "answer": "Phishing is a cyberattack tricking users to reveal sensitive data." },
  "what is malware": { "answer": "Malware is malicious software designed to harm systems." },
  "what is virus": { "answer": "A computer virus is a malicious program that spreads by infecting files." },
  "what is worm": { "answer": "A worm is malware that spreads without human action." },
  "what is trojan": { "answer": "A Trojan disguises itself as legitimate software to harm systems." },
  "what is ransomware": { "answer": "Ransomware encrypts data and demands ransom for decryption." },
  "what is spyware": { "answer": "Spyware secretly collects information from a user’s system." },
  "what is adware": { "answer": "Adware shows unwanted advertisements to users." },
  "what is botnet": { "answer": "A botnet is a network of infected computers controlled remotely." },
  "what is zero day attack": { "answer": "A zero-day attack exploits a vulnerability before it is patched." },
  "what is penetration testing": { "answer": "Penetration testing is simulated hacking to test security." },
  "what is vulnerability": { "answer": "A vulnerability is a weakness in a system that attackers exploit." },
  "what is exploit": { "answer": "An exploit is a method of taking advantage of a vulnerability." },
  "what is encryption": { "answer": "Encryption converts plain text into unreadable form to secure data." },
  "what is decryption": { "answer": "Decryption converts encrypted data back to plain text." },
  "what is symmetric encryption": { "answer": "Symmetric encryption uses the same key for encryption and decryption." },
  "what is asymmetric encryption": { "answer": "Asymmetric encryption uses public and private keys." },
  "what is ssl": { "answer": "SSL is Secure Sockets Layer for encrypted web communication." },
  "what is tls": { "answer": "TLS is Transport Layer Security, the successor of SSL." },
  "what is digital signature": { "answer": "A digital signature verifies authenticity and integrity of data." },
  "what is blockchain mining": { "answer": "Mining validates blockchain transactions by solving cryptographic puzzles." },
  "what is nft": { "answer": "NFTs are Non-Fungible Tokens representing unique digital assets." },
  "what is smart contract": { "answer": "A smart contract is a self-executing agreement on blockchain." },
  "what is cloud storage": { "answer": "Cloud storage saves data on remote servers accessible via the internet." },
  "what is hybrid cloud": { "answer": "Hybrid cloud combines private and public cloud services." },
  "what is edge computing": { "answer": "Edge computing processes data closer to the source of data generation." },
  "what is serverless computing": { "answer": "Serverless computing lets developers run code without managing servers." },
  "what is microservices": { "answer": "Microservices is an architecture dividing applications into small services." },
  "what is monolithic architecture": { "answer": "Monolithic architecture builds software as one large unit." },
  "what is ci cd": { "answer": "CI/CD stands for Continuous Integration and Continuous Deployment." },
  "what is version control": { "answer": "Version control tracks changes in code over time." },
  "what is svn": { "answer": "SVN is Subversion, a centralized version control system." },
  "what is distributed system": { "answer": "A distributed system has multiple computers working together." },
  "what is peer to peer network": { "answer": "P2P network connects computers directly without a central server." },
  "what is client server architecture": { "answer": "Client-server architecture separates clients from central servers." },
  "what is api gateway": { "answer": "An API gateway manages and routes API requests." },
  "what is middleware": { "answer": "Middleware is software that connects applications and services." },
  "what is data warehouse": { "answer": "A data warehouse stores historical data for analysis." },
  "what is data lake": { "answer": "A data lake stores raw structured and unstructured data." },
  "what is etl": { "answer": "ETL stands for Extract, Transform, Load in data pipelines." },
  "what is oltp": { "answer": "OLTP is Online Transaction Processing, handling day-to-day transactions." },
  "what is olap": { "answer": "OLAP is Online Analytical Processing for complex queries and analysis." },
  "what is bigquery": { "answer": "BigQuery is Google’s serverless data warehouse." },
  "what is snowflake": { "answer": "Snowflake is a cloud-based data warehousing platform." },
  "what is hadoop": { "answer": "Hadoop is a framework for distributed storage and big data processing." },
  "what is spark": { "answer": "Apache Spark is a big data processing engine." },
  "what is kafka": { "answer": "Kafka is a distributed event streaming platform." },
  "what is airflow": { "answer": "Apache Airflow is a platform to schedule and monitor workflows." },
  "what is tableau": { "answer": "Tableau is a data visualization tool." },
  "what is powerbi": { "answer": "Power BI is Microsoft’s business analytics tool." },
  "what is excel": { "answer": "Excel is a spreadsheet program by Microsoft for data organization." },
  "what is ms word": { "answer": "MS Word is a word processing program by Microsoft." },
  "what is ms powerpoint": { "answer": "PowerPoint is Microsoft’s tool for creating presentations." },
  "what is photoshop": { "answer": "Photoshop is Adobe’s image editing software." },
  "what is figma": { "answer": "Figma is a collaborative interface design tool." },
  "what is canva": { "answer": "Canva is an online design and publishing platform." },
  "what is ui ux": { "answer": "UI is User Interface, UX is User Experience in product design." },
  "what is responsive design": { "answer": "Responsive design makes websites adjust to different screen sizes." },
  "what is accessibility": { "answer": "Accessibility ensures software is usable by people with disabilities." },
  "what is seo": { "answer": "SEO is Search Engine Optimization to rank higher in search engines." },
  "what is sem": { "answer": "SEM is Search Engine Marketing using paid ads." },
  "what is digital marketing": { "answer": "Digital marketing promotes products/services via online channels." },
  "what is content marketing": { "answer": "Content marketing focuses on creating valuable content to attract audiences." },
  "what is influencer marketing": { "answer": "Influencer marketing uses popular individuals to promote products." },
  "what is social media marketing": { "answer": "SMM is using social platforms to promote brands." },
  "what is email marketing": { "answer": "Email marketing involves sending promotional messages to subscribers." },
  "what is affiliate marketing": { "answer": "Affiliate marketing pays commissions to promote products." },
  "what is crm": { "answer": "CRM is Customer Relationship Management software." },
  "what is erp": { "answer": "ERP is Enterprise Resource Planning software integrating business processes." },
  "what is sap": { "answer": "SAP is a leading ERP software company." },
  "what is hrm": { "answer": "HRM is Human Resource Management system for employee data." },
  "what is fintech": { "answer": "Fintech combines finance and technology to improve services." },
  "what is insurtech": { "answer": "Insurtech uses technology to improve insurance services." },
  "what is edtech": { "answer": "Edtech uses digital technology in education." },
  "what is healthtech": { "answer": "Healthtech applies technology to improve healthcare." },
  "what is agritech": { "answer": "Agritech applies technology in agriculture to improve productivity." },
  "what is iot": { "answer": "IoT is Internet of Things, connecting devices to the internet." },
  "what is smart home": { "answer": "Smart homes use IoT devices for automation and control." },
  "what is wearable technology": { "answer": "Wearables are devices like smartwatches and fitness trackers." },
  "what is autonomous vehicle": { "answer": "An autonomous vehicle drives itself using AI and sensors." },
  "what is drone": { "answer": "A drone is an unmanned aerial vehicle controlled remotely or autonomously." },
  "what is robotics": { "answer": "Robotics is the science of designing and building robots." },
  "what is humanoid robot": { "answer": "A humanoid robot mimics human appearance and movements." },
  "what is industrial robot": { "answer": "Industrial robots are used in factories for manufacturing tasks." },
  "what is ai": { "answer": "AI is Artificial Intelligence, making machines mimic human intelligence." },
  "what is machine learning": { "answer": "Machine learning enables systems to learn patterns from data." },
  "what is deep learning": { "answer": "Deep learning is a subset of ML using neural networks with many layers." },
  "what is neural network": { "answer": "A neural network is a model inspired by the human brain." },
  "what is computer vision": { "answer": "Computer vision enables machines to understand images and videos." },
  "what is natural language processing": { "answer": "NLP is the ability of machines to understand and process human language." },
  "what is reinforcement learning": { "answer": "Reinforcement learning trains agents through rewards and penalties." },
  "what is supervised learning": { "answer": "Supervised learning uses labeled data to train models." },
  "what is unsupervised learning": { "answer": "Unsupervised learning finds hidden patterns in unlabeled data." },
  "what is semi supervised learning": { "answer": "Semi-supervised learning uses both labeled and unlabeled data." },
  "what is generative ai": { "answer": "Generative AI creates new content like text, images, and music." },
  "what is gpt": { "answer": "GPT is a Generative Pre-trained Transformer model for text." },
  "what is chatgpt": { "answer": "ChatGPT is a conversational AI based on GPT." },
  "what is bert": { "answer": "BERT is a language model by Google for NLP tasks." },
  "what is transformers": { "answer": "Transformers are deep learning models designed for sequence data." },
  "what is llm": { "answer": "LLM stands for Large Language Model, trained on massive text data." },
  "what is stable diffusion": { "answer": "Stable Diffusion is an AI model for generating images from text." },
  "what is midjourney": { "answer": "MidJourney is an AI tool for generating artistic images." },
  "what is dalle": { "answer": "DALL·E is OpenAI’s AI model that generates images from text." },
  "what is autonomous ai agent": { "answer": "An autonomous AI agent can make decisions and act independently." },
  "what is prompt engineering": { "answer": "Prompt engineering is crafting inputs to get desired outputs from AI." },
  "what is fine tuning": { "answer": "Fine-tuning adjusts a pre-trained model on specific data." },
  "what is transfer learning": { "answer": "Transfer learning reuses a pre-trained model for a related task." },
  "what is overfitting": { "answer": "Overfitting happens when a model memorizes training data but fails on new data." },
  "what is underfitting": { "answer": "Underfitting happens when a model is too simple to capture patterns." },
  "what is bias in ai": { "answer": "Bias in AI means unfair or skewed results due to biased data." },
  "what is variance in ml": { "answer": "Variance is how much a model's predictions change with different data." },
  "what is precision in ml": { "answer": "Precision measures how many positive predictions were correct." },
  "what is recall in ml": { "answer": "Recall measures how many actual positives were detected." },
  "what is f1 score": { "answer": "F1 score balances precision and recall." },
  "what is confusion matrix": { "answer": "A confusion matrix shows performance of a classification model." },
  "what is roc curve": { "answer": "ROC curve visualizes performance of a binary classifier." },
  "what is auc": { "answer": "AUC is Area Under the ROC Curve, measuring classifier performance." },
  "what is hyperparameter": { "answer": "Hyperparameters are settings that control model training." },
  "what is feature engineering": { "answer": "Feature engineering creates new input variables from raw data." },
  "what is dimensionality reduction": { "answer": "Dimensionality reduction reduces number of features while keeping information." },
  "what is pca": { "answer": "PCA (Principal Component Analysis) is a dimensionality reduction technique." },
  "what is clustering": { "answer": "Clustering groups similar data points together." },
  "what is kmeans": { "answer": "K-means is a clustering algorithm dividing data into k groups." },
  "what is decision tree": { "answer": "A decision tree is a model that splits data into branches for prediction." },
  "what is random forest": { "answer": "Random forest is an ensemble of decision trees." },
  "what is gradient boosting": { "answer": "Gradient boosting builds models sequentially to improve performance." },
  "what is xgboost": { "answer": "XGBoost is a high-performance gradient boosting library." },
  "what is lightgbm": { "answer": "LightGBM is a fast gradient boosting framework by Microsoft." },
  "what is catboost": { "answer": "CatBoost is a gradient boosting library by Yandex." },
  "what is svm": { "answer": "SVM is a Support Vector Machine used for classification tasks." },
  "what is knn": { "answer": "KNN is K-Nearest Neighbors, a simple classification algorithm." },
  "what is naive bayes": { "answer": "Naive Bayes is a probabilistic classifier based on Bayes’ theorem." },
  "what is linear regression": { "answer": "Linear regression models the relationship between variables with a straight line." },
  "what is logistic regression": { "answer": "Logistic regression is used for binary classification." },
  "what is regression analysis": { "answer": "Regression analysis studies relationships between dependent and independent variables." },
  "what is anomaly detection": { "answer": "Anomaly detection identifies rare items or events in data." },
  "what is recommendation system": { "answer": "Recommendation systems suggest items based on user behavior." },
  "what is collaborative filtering": { "answer": "Collaborative filtering recommends items based on similar users." },
  "what is content based filtering": { "answer": "Content-based filtering recommends items based on attributes." },
  "what is hybrid recommender system": { "answer": "A hybrid recommender combines collaborative and content-based methods." },
  "what is reinforcement agent": { "answer": "A reinforcement agent learns by interacting with an environment." },
  "what is q learning": { "answer": "Q-learning is a reinforcement learning algorithm using Q-values." },
  "what is policy gradient": { "answer": "Policy gradient is a reinforcement learning method optimizing policies." },
  "what is markov decision process": { "answer": "MDP models decision-making in reinforcement learning with states, actions, rewards." },
  "what is dataset": { "answer": "A dataset is a collection of data used for training or analysis." },
  "what is training data": { "answer": "Training data is used to fit machine learning models." },
  "what is testing data": { "answer": "Testing data evaluates model performance." },
  "what is validation data": { "answer": "Validation data tunes model hyperparameters." },
  "what is cross validation": { "answer": "Cross-validation splits data to test model performance on different subsets." },
  "what is batch size": { "answer": "Batch size is the number of samples processed before updating the model." },
  "what is epoch": { "answer": "An epoch is one complete pass through the training dataset." },
  "what is learning rate": { "answer": "Learning rate controls how fast a model updates during training." },
  "what is optimizer": { "answer": "An optimizer adjusts weights to minimize loss function." },
  "what is loss function": { "answer": "A loss function measures how wrong the model predictions are." },
  "what is gradient descent": { "answer": "Gradient descent is an optimization algorithm minimizing loss." },
  "what is stochastic gradient descent": { "answer": "SGD updates weights using a single sample at a time." },
  "what is adam optimizer": { "answer": "Adam is an optimization algorithm combining momentum and RMSProp." },
  "what is dropout": { "answer": "Dropout prevents overfitting by randomly dropping neurons during training." },
  "what is batch normalization": { "answer": "Batch normalization normalizes inputs of each layer to speed up training." },
  "what is activation function": { "answer": "Activation functions introduce non-linearity into neural networks." },
  "what is relu": { "answer": "ReLU is a popular activation function that outputs max(0,x)." },
  "what is sigmoid": { "answer": "Sigmoid activation maps values between 0 and 1." },
  "what is tanh": { "answer": "Tanh activation maps values between -1 and 1." },
  "what is softmax": { "answer": "Softmax activation outputs probabilities for multiple classes." },
  "what is cnn": { "answer": "CNN is a Convolutional Neural Network used for image processing." },
  "what is rnn": { "answer": "RNN is a Recurrent Neural Network for sequential data." },
  "what is lstm": { "answer": "LSTM is a type of RNN handling long-term dependencies." },
  "what is gru": { "answer": "GRU is a Gated Recurrent Unit, a simplified LSTM." },
  "what is gan": { "answer": "GANs are Generative Adversarial Networks used to create new data." },
  "what is autoencoder": { "answer": "Autoencoders learn compressed representations of data." },
  "what is cloud computing": { "answer": "Cloud computing delivers computing services over the internet." },
  "what is aws": { "answer": "AWS (Amazon Web Services) is a cloud service provider by Amazon." },
  "what is azure": { "answer": "Microsoft Azure is a cloud computing platform." },
  "what is google cloud": { "answer": "Google Cloud Platform (GCP) is Google’s cloud service." },
  "what is saas": { "answer": "SaaS means Software as a Service, applications delivered over the internet." },
  "what is paas": { "answer": "PaaS means Platform as a Service, providing tools for developers." },
  "what is iaas": { "answer": "IaaS means Infrastructure as a Service, providing virtualized computing resources." },
  "what is serverless computing": { "answer": "Serverless computing lets you run code without managing servers." },
  "what is container": { "answer": "Containers package applications with their dependencies for consistency." },
  "what is docker": { "answer": "Docker is a platform for developing and running applications in containers." },
  "what is kubernetes": { "answer": "Kubernetes is a system for managing containerized applications." },
  "what is microservices": { "answer": "Microservices is an architecture where apps are built as small services." },
  "what is monolith": { "answer": "A monolith is a single-tiered application where all parts are interconnected." },
  "what is api": { "answer": "API stands for Application Programming Interface, enabling communication between systems." },
  "what is rest api": { "answer": "REST API follows REST principles for communication using HTTP methods." },
  "what is graphql": { "answer": "GraphQL is a query language for APIs created by Facebook." },
  "what is soap": { "answer": "SOAP is a protocol for exchanging structured data in web services." },
  "what is web socket": { "answer": "WebSocket enables real-time, two-way communication between client and server." },
  "what is http": { "answer": "HTTP is Hypertext Transfer Protocol used for communication on the web." },
  "what is https": { "answer": "HTTPS is HTTP with encryption using SSL/TLS." },
  "what is dns": { "answer": "DNS translates domain names into IP addresses." },
  "what is ip address": { "answer": "An IP address identifies a device on a network." },
  "what is ipv4": { "answer": "IPv4 is the fourth version of Internet Protocol using 32-bit addresses." },
  "what is ipv6": { "answer": "IPv6 is the sixth version of Internet Protocol using 128-bit addresses." },
  "what is tcp": { "answer": "TCP is Transmission Control Protocol ensuring reliable communication." },
  "what is udp": { "answer": "UDP is User Datagram Protocol, faster but less reliable than TCP." },
  "what is firewall": { "answer": "A firewall protects networks by filtering traffic." },
  "what is vpn": { "answer": "VPN is Virtual Private Network, securing internet connections." },
  "what is proxy server": { "answer": "A proxy server acts as an intermediary between client and server." },
  "what is load balancer": { "answer": "A load balancer distributes traffic across multiple servers." },
  "what is cdn": { "answer": "CDN is Content Delivery Network, delivering content closer to users." },
  "what is cache": { "answer": "Cache stores frequently accessed data for faster retrieval." },
  "what is redis": { "answer": "Redis is an in-memory data store used for caching and more." },
  "what is memcached": { "answer": "Memcached is a distributed memory caching system." },
  "what is database replication": { "answer": "Replication copies data from one database to another." },
  "what is database sharding": { "answer": "Sharding splits a database into smaller, faster pieces." },
  "what is sql injection": { "answer": "SQL injection is a cyberattack where malicious SQL code is used." },
  "what is xss": { "answer": "XSS (Cross-Site Scripting) is an attack injecting malicious scripts." },
  "what is csrf": { "answer": "CSRF (Cross-Site Request Forgery) tricks users into unwanted actions." },
  "what is ransomware": { "answer": "Ransomware is malware that locks data and demands payment." },
  "what is phishing": { "answer": "Phishing is a fraud attempt to steal sensitive information." },
  "what is ddos attack": { "answer": "DDoS attack overwhelms a server with traffic to make it unavailable." },
  "what is brute force attack": { "answer": "Brute force tries all possible passwords to gain access." },
  "what is encryption": { "answer": "Encryption converts data into unreadable form to protect it." },
  "what is decryption": { "answer": "Decryption converts encrypted data back to readable form." },
  "what is hashing": { "answer": "Hashing generates a fixed-size value from input data." },
  "what is symmetric encryption": { "answer": "Symmetric encryption uses one key for both encryption and decryption." },
  "what is asymmetric encryption": { "answer": "Asymmetric encryption uses public and private keys." },
  "what is rsa": { "answer": "RSA is an asymmetric cryptographic algorithm." },
  "what is aes": { "answer": "AES is Advanced Encryption Standard, a symmetric encryption method." },
  "what is blockchain": { "answer": "Blockchain is a decentralized ledger technology." },
  "what is cryptocurrency": { "answer": "Cryptocurrency is digital money built on blockchain." },
  "what is bitcoin": { "answer": "Bitcoin is the first and most well-known cryptocurrency." },
  "what is ethereum": { "answer": "Ethereum is a blockchain supporting smart contracts." },
  "what is smart contract": { "answer": "Smart contracts are self-executing contracts on blockchain." },
  "what is nft": { "answer": "NFT is a Non-Fungible Token representing digital ownership." },
  "what is defi": { "answer": "DeFi is Decentralized Finance using blockchain for financial services." },
  "what is fintech": { "answer": "FinTech is Financial Technology improving financial services." },
  "what is stock market": { "answer": "Stock market is where shares of companies are traded." },
  "what is ipo": { "answer": "IPO is Initial Public Offering, when a company first sells shares." },
  "what is mutual fund": { "answer": "Mutual fund pools money from investors to buy securities." },
  "what is etf": { "answer": "ETF is Exchange-Traded Fund, traded like a stock on exchanges." },
  "what is bond": { "answer": "A bond is a fixed-income investment representing a loan." },
  "what is dividend": { "answer": "A dividend is a portion of company profits paid to shareholders." },
  "what is inflation": { "answer": "Inflation is the rise in prices reducing purchasing power." },
  "what is deflation": { "answer": "Deflation is a decrease in general price levels." },
  "what is gdp": { "answer": "GDP is Gross Domestic Product, measuring a country’s economic output." },
  "what is recession": { "answer": "Recession is a decline in economic activity for two quarters." },
  "what is depression": { "answer": "Depression is a severe and prolonged economic downturn." },
  "what is unemployment": { "answer": "Unemployment is the percentage of jobless people seeking work." },
  "what is monetary policy": { "answer": "Monetary policy controls money supply and interest rates." },
  "what is fiscal policy": { "answer": "Fiscal policy uses government spending and taxation." },
  "what is interest rate": { "answer": "Interest rate is the cost of borrowing money." },
  "what is exchange rate": { "answer": "Exchange rate is the value of one currency compared to another." },
  "what is forex": { "answer": "Forex is the global market for trading currencies." },
  "what is import": { "answer": "Import is bringing goods into a country from abroad." },
  "what is export": { "answer": "Export is sending goods from one country to another." },
  "what is trade deficit": { "answer": "Trade deficit happens when imports exceed exports." },
  "what is trade surplus": { "answer": "Trade surplus happens when exports exceed imports." },
  "what is wto": { "answer": "WTO is the World Trade Organization regulating global trade." },
  "what is imf": { "answer": "IMF is the International Monetary Fund providing financial aid." },
  "what is world bank": { "answer": "The World Bank funds projects to reduce poverty worldwide." },
  "what is un": { "answer": "UN is the United Nations, an international organization for peace." },
  "what is nato": { "answer": "NATO is the North Atlantic Treaty Organization, a military alliance." },
  "what is eu": { "answer": "EU is the European Union, a political and economic union of countries." },
  "what is asean": { "answer": "ASEAN is the Association of Southeast Asian Nations." },
  "what is saarc": { "answer": "SAARC is the South Asian Association for Regional Cooperation." },
  "what is brics": { "answer": "BRICS is a group of countries: Brazil, Russia, India, China, South Africa." },
  "what is opec": { "answer": "OPEC is the Organization of Petroleum Exporting Countries." },
  "what is climate change": { "answer": "Climate change refers to long-term shifts in global temperatures." },
  "what is greenhouse effect": { "answer": "The greenhouse effect traps heat in the Earth’s atmosphere." },
  "what is global warming": { "answer": "Global warming is the rise in Earth’s average temperature." },
  "what is carbon footprint": { "answer": "Carbon footprint is the total greenhouse gases produced by an individual or entity." },
  "what is renewable energy": { "answer": "Renewable energy comes from sources like solar, wind, and water." },
  "what is non renewable energy": { "answer": "Non-renewable energy comes from coal, oil, and natural gas." },
  "what is solar energy": { "answer": "Solar energy is generated from sunlight using solar panels." },
  "what is wind energy": { "answer": "Wind energy is generated using wind turbines." },
  "what is hydro power": { "answer": "Hydropower generates electricity from flowing water." },
  "what is geothermal energy": { "answer": "Geothermal energy comes from heat inside the Earth." },
  "what is biomass energy": { "answer": "Biomass energy comes from organic matter like plants and waste." },
  "what is tidal energy": { "answer": "Tidal energy is generated from ocean tides." },
  "what is nuclear energy": { "answer": "Nuclear energy is generated from splitting atoms in reactors." },
  "what is fossil fuel": { "answer": "Fossil fuels are natural fuels like coal, oil, and gas." },
  "what is petroleum": { "answer": "Petroleum is crude oil extracted from the earth." },
  "what is natural gas": { "answer": "Natural gas is a fossil fuel mainly consisting of methane." },
  "what is coal": { "answer": "Coal is a fossil fuel formed from plants over millions of years." },
  "what is mining": { "answer": "Mining is extracting minerals and resources from the Earth." },
  "what is metallurgy": { "answer": "Metallurgy is the science of extracting and processing metals." },
  "what is alloy": { "answer": "An alloy is a mixture of two or more metals." },
  "what is steel": { "answer": "Steel is an alloy of iron and carbon." },
  "what is stainless steel": { "answer": "Stainless steel is steel with chromium, resistant to rust." },
  "what is bronze": { "answer": "Bronze is an alloy of copper and tin." },
  "what is brass": { "answer": "Brass is an alloy of copper and zinc." },
  "what is aluminum": { "answer": "Aluminum is a lightweight, corrosion-resistant metal." },
  "what is copper": { "answer": "Copper is a red-brown metal used in electrical wiring." },
  "what is gold": { "answer": "Gold is a precious metal used for jewelry and investment." },
  "what is silver": { "answer": "Silver is a precious metal used in jewelry and electronics." },
  "what is platinum": { "answer": "Platinum is a rare precious metal used in industry and jewelry." },
  "what is diamond": { "answer": "Diamond is a crystalline form of carbon, the hardest natural substance." },
  "what is gemstone": { "answer": "A gemstone is a precious or semi-precious mineral used in jewelry." },
  "what is pearl": { "answer": "A pearl is formed inside oysters from calcium carbonate." },
  "what is crystal": { "answer": "A crystal is a solid with atoms arranged in repeating patterns." },
  "what is glass": { "answer": "Glass is a transparent material made from sand and silica." },
  "what is ceramic": { "answer": "Ceramics are non-metallic, heat-resistant materials made from clay." },
  "what is plastic": { "answer": "Plastic is a synthetic material made from polymers." },
  "what is polymer": { "answer": "A polymer is a large molecule made from repeating units." },
  "what is rubber": { "answer": "Rubber is an elastic material from latex or synthetic sources." },
  "what is paper": { "answer": "Paper is made from processed plant fibers, usually wood pulp." },
  "what is textile": { "answer": "Textiles are woven or knitted fabrics from fibers." },
  "what is cotton": { "answer": "Cotton is a natural fiber from cotton plants." },
  "what is wool": { "answer": "Wool is a fiber from sheep and other animals." },
  "what is silk": { "answer": "Silk is a natural fiber made by silkworms." },
  "what is polyester": { "answer": "Polyester is a synthetic fiber used in fabrics." },
  "what is nylon": { "answer": "Nylon is a strong synthetic polymer used in textiles." },
  "what is rayon": { "answer": "Rayon is a semi-synthetic fiber made from cellulose." },
  "what is leather": { "answer": "Leather is made from animal hides processed by tanning." },
  "what is fur": { "answer": "Fur is the thick hair coat of animals used for clothing." },
  "what is fashion": { "answer": "Fashion is the style of clothing and accessories popular at a time." },
  "what is costume": { "answer": "A costume is clothing worn for cultural or special purposes." },
  "what is uniform": { "answer": "A uniform is a standard set of clothes worn by members of an organization." },
  "what is traditional dress": { "answer": "Traditional dress refers to clothing specific to a culture or region." },
  "what is casual wear": { "answer": "Casual wear is everyday comfortable clothing." },
  "what is formal wear": { "answer": "Formal wear is elegant clothing for ceremonies or events." },
  "what is sportswear": { "answer": "Sportswear is clothing designed for physical activities." },
  "what is footwear": { "answer": "Footwear refers to shoes, sandals, boots, etc." },
  "what is accessory": { "answer": "An accessory is an item that complements an outfit." },
  "what is jewelry": { "answer": "Jewelry includes ornaments like rings, necklaces, and bracelets." },
  "what is watch": { "answer": "A watch is a timepiece worn on the wrist." },
  "what is sunglasses": { "answer": "Sunglasses are glasses that protect eyes from sunlight." },
  "what is hat": { "answer": "A hat is a head covering worn for style or protection." },
  "what is helmet": { "answer": "A helmet is protective headgear used for safety." },
  "what is bag": { "answer": "A bag is a container for carrying items." },
  "what is wallet": { "answer": "A wallet is a small case for money and cards." },
  "what is belt": { "answer": "A belt is a strap worn around the waist." },
  "what is tie": { "answer": "A tie is a strip of fabric worn around the neck with shirts." },
  "what is scarf": { "answer": "A scarf is fabric worn around the neck for warmth or style." },
  "what is makeup": { "answer": "Makeup is cosmetics applied to the face to enhance appearance." },
  "what is skincare": { "answer": "Skincare involves practices to maintain healthy skin." },
  "what is hairstyle": { "answer": "Hairstyle is the way hair is cut or arranged." },
  "what is perfume": { "answer": "Perfume is a fragrant liquid applied to the body." },
  "what is deodorant": { "answer": "Deodorant is a product to reduce body odor." },
  "what is shampoo": { "answer": "Shampoo is a liquid for cleaning hair." },
  "what is conditioner": { "answer": "Conditioner is applied to hair to make it smooth and soft." },
  "what is soap": { "answer": "Soap is a cleaning product made from fats and alkalis." },
  "what is detergent": { "answer": "Detergent is a cleaning agent used for washing clothes and dishes." },
  "what is toothpaste": { "answer": "Toothpaste is used with a toothbrush to clean teeth." },
  "what is toothbrush": { "answer": "A toothbrush is a small brush for cleaning teeth." },
  "what is mouthwash": { "answer": "Mouthwash is a liquid for oral hygiene." },
  "what is comb": { "answer": "A comb is a tool for arranging hair." },
  "what is mirror": { "answer": "A mirror is a reflective surface showing images." },
  "what is towel": { "answer": "A towel is fabric used to dry the body." },
  "what is bed": { "answer": "A bed is furniture for sleeping." },
  "what is mattress": { "answer": "A mattress is a cushioned support for sleeping." },
  "what is pillow": { "answer": "A pillow is a soft support for the head while sleeping." },
  "what is blanket": { "answer": "A blanket is fabric for warmth while sleeping." },
  "what is bedsheet": { "answer": "A bedsheet is fabric covering a mattress." },
  "what is sofa": { "answer": "A sofa is upholstered seating furniture for multiple people." },
  "what is chair": { "answer": "A chair is seating furniture for one person." },
  "what is table": { "answer": "A table is furniture with a flat surface supported by legs." },
  "what is cupboard": { "answer": "A cupboard is furniture with shelves for storage." },
  "what is wardrobe": { "answer": "A wardrobe is tall furniture for storing clothes." },
  "what is shelf": { "answer": "A shelf is a flat surface attached to walls or furniture for storage." },
  "what is desk": { "answer": "A desk is a table used for writing or work." },
  "what is computer desk": { "answer": "A computer desk is designed to hold a computer and accessories." },
  "what is dining table": { "answer": "A dining table is a table for eating meals." },
  "what is coffee table": { "answer": "A coffee table is a low table placed in living rooms." },
  "what is lamp": { "answer": "A lamp is a device that produces light." },
  "what is fan": { "answer": "A fan is a device that circulates air." },
  "what is air conditioner": { "answer": "An air conditioner is a device that cools indoor air." },
  "what is refrigerator": { "answer": "A refrigerator keeps food and drinks cold." },
  "what is washing machine": { "answer": "A washing machine washes clothes automatically." },
  "what is microwave": { "answer": "A microwave is an appliance that heats food quickly using waves." },
  "what is oven": { "answer": "An oven is an appliance for baking and cooking food." },
  "what is mixer": { "answer": "A mixer is a device that blends or beats ingredients." },
  "what is grinder": { "answer": "A grinder is a device that crushes or grinds substances." },
  "what is blender": { "answer": "A blender is an appliance for mixing and pureeing food." },
  "what is toaster": { "answer": "A toaster is an appliance for browning bread slices." },
  "print hello world program in python": {
    "answer": "Use print function.\nCode:\n```python\nprint('Hello, World!')\n```"
  },
  "write a program to find factorial of a number": {
    "answer": "Factorial can be solved using recursion or loops.\nCode:\n```python\ndef factorial(n):\n    return 1 if n==0 else n*factorial(n-1)\nprint(factorial(5))\n```\nOutput: 120"
  },
  "write a program to check if a number is prime": {
    "answer": "Prime check requires checking divisibility.\nCode:\n```python\ndef is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n**0.5)+1):\n        if n % i == 0:\n            return False\n    return True\nprint(is_prime(7))\n```\nOutput: True"
  },
  "write a program to reverse a string": {
    "answer": "String slicing can reverse easily.\nCode:\n```python\ns = 'hello'\nprint(s[::-1])\n```\nOutput: 'olleh'"
  },
  "write a program to find fibonacci series up to n": {
    "answer": "Use iteration to generate Fibonacci numbers.\nCode:\n```python\ndef fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        print(a, end=' ')\n        a, b = b, a+b\nfibonacci(7)\n```\nOutput: 0 1 1 2 3 5 8"
  },
  "write a program to check palindrome string": {
    "answer": "Palindrome means string reads same forward/backward.\nCode:\n```python\ndef is_palindrome(s):\n    return s == s[::-1]\nprint(is_palindrome('madam'))\n```\nOutput: True"
  },
  "write a program to find gcd of two numbers": {
    "answer": "Use Euclidean algorithm.\nCode:\n```python\ndef gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\nprint(gcd(48, 18))\n```\nOutput: 6"
  },
  "write a program to sort a list": {
    "answer": "Python has inbuilt sorted function.\nCode:\n```python\narr = [5, 2, 9, 1]\nprint(sorted(arr))\n```\nOutput: [1, 2, 5, 9]"
  },
  "write a program to count vowels in a string": {
    "answer": "Loop through string and count vowels.\nCode:\n```python\ns = 'hello world'\nvowels = 'aeiou'\ncount = sum(1 for c in s if c in vowels)\nprint(count)\n```\nOutput: 3"
  },
  "write a program to find largest element in list": {
    "answer": "Use max() function or loop.\nCode:\n```python\narr = [10, 20, 4, 45, 99]\nprint(max(arr))\n```\nOutput: 99"
  },

  "print hello world program in python": {
    "answer": "Code:\n```python\nprint('Hello, World!')\n```\nOutput:\nHello, World!"
  },
  "write a program to find factorial of a number": {
    "answer": "Code:\n```python\ndef factorial(n):\n    if n == 0 or n == 1:\n        return 1\n    else:\n        return n * factorial(n - 1)\n\nprint(factorial(5))\n```\nOutput:\n120"
  },
  "write a program to check if a number is prime": {
    "answer": "Code:\n```python\ndef is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n ** 0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\nprint(is_prime(7))\n```\nOutput:\nTrue"
  },
  "write a program to reverse a string": {
    "answer": "Code:\n```python\ns = 'hello'\nreversed_str = s[::-1]\nprint(reversed_str)\n```\nOutput:\nolleh"
  },
  "write a program to find fibonacci series up to n terms": {
    "answer": "Code:\n```python\ndef fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        print(a, end=' ')\n        a, b = b, a + b\n\nfibonacci(7)\n```\nOutput:\n0 1 1 2 3 5 8"
  },
  "write a program to check if a string is palindrome": {
    "answer": "Code:\n```python\ndef is_palindrome(s):\n    return s == s[::-1]\n\nprint(is_palindrome('madam'))\n```\nOutput:\nTrue"
  },
  "write a program to find gcd of two numbers": {
    "answer": "Code:\n```python\ndef gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\n\nprint(gcd(48, 18))\n```\nOutput:\n6"
  },
  "write a program to sort a list in ascending order": {
    "answer": "Code:\n```python\narr = [5, 2, 9, 1]\narr.sort()\nprint(arr)\n```\nOutput:\n[1, 2, 5, 9]"
  },
  "write a program to count vowels in a string": {
    "answer": "Code:\n```python\ns = 'hello world'\nvowels = 'aeiou'\ncount = sum(1 for c in s if c in vowels)\nprint(count)\n```\nOutput:\n3"
  },
  "write a program to find the largest element in a list": {
    "answer": "Code:\n```python\narr = [10, 20, 4, 45, 99]\nprint(max(arr))\n```\nOutput:\n99"
  },
  "print hello world program in python": {
    "answer": "Code:\n```python\nprint('Hello, World!')\n```\nOutput:\nHello, World!\n\nReference: https://www.w3schools.com/python/ref_func_print.asp"
  },
  "write a program to find factorial of a number": {
    "answer": "Code:\n```python\ndef factorial(n):\n    if n == 0 or n == 1:\n        return 1\n    else:\n        return n * factorial(n - 1)\n\nprint(factorial(5))\n```\nOutput:\n120\n\nReference: https://www.geeksforgeeks.org/python-program-for-factorial-of-a-number/"
  },
  "write a program to check if a number is prime": {
    "answer": "Code:\n```python\ndef is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n ** 0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\nprint(is_prime(7))\n```\nOutput:\nTrue\n\nReference: https://www.programiz.com/python-programming/examples/prime-number"
  },
  "write a program to reverse a string": {
    "answer": "Code:\n```python\ns = 'hello'\nreversed_str = s[::-1]\nprint(reversed_str)\n```\nOutput:\nolleh\n\nReference: https://www.geeksforgeeks.org/python-program-to-reverse-a-string/"
  },
  "write a program to find fibonacci series up to n terms": {
    "answer": "Code:\n```python\ndef fibonacci(n):\n    a, b = 0, 1\n    for _ in range(n):\n        print(a, end=' ')\n        a, b = b, a + b\n\nfibonacci(7)\n```\nOutput:\n0 1 1 2 3 5 8\n\nReference: https://www.programiz.com/python-programming/examples/fibonacci-sequence"
  },
  "write a program to check if a string is palindrome": {
    "answer": "Code:\n```python\ndef is_palindrome(s):\n    return s == s[::-1]\n\nprint(is_palindrome('madam'))\n```\nOutput:\nTrue\n\nReference: https://www.geeksforgeeks.org/python-program-to-check-whether-a-string-is-palindrome-or-not/"
  },
  "write a program to find gcd of two numbers": {
    "answer": "Code:\n```python\ndef gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\n\nprint(gcd(48, 18))\n```\nOutput:\n6\n\nReference: https://www.programiz.com/python-programming/examples/hcf-gcd"
  },
  "write a program to sort a list in ascending order": {
    "answer": "Code:\n```python\narr = [5, 2, 9, 1]\narr.sort()\nprint(arr)\n```\nOutput:\n[1, 2, 5, 9]\n\nReference: https://www.w3schools.com/python/ref_list_sort.asp"
  },
  "write a program to count vowels in a string": {
    "answer": "Code:\n```python\ns = 'hello world'\nvowels = 'aeiou'\ncount = sum(1 for c in s if c in vowels)\nprint(count)\n```\nOutput:\n3\n\nReference: https://www.geeksforgeeks.org/program-count-vowels-string-iterative-recursive/"
  },
  "write a program to find the largest element in a list": {
    "answer": "Code:\n```python\narr = [10, 20, 4, 45, 99]\nprint(max(arr))\n```\nOutput:\n99\n\nReference: https://www.programiz.com/python-programming/examples/largest-number"
  },

    "what is business development": {
    "answer": "Business development is the process of identifying growth opportunities, building partnerships, and creating strategies to increase revenue and market reach.\n\nReference: https://www.investopedia.com/terms/b/business-development.asp"
  },
  "what is market research": {
    "answer": "Market research is the process of collecting and analyzing information about customers, competitors, and industry trends to make better business decisions.\n\nReference: https://www.surveymonkey.com/mp/market-research/"
  },
  "what is crm": {
    "answer": "CRM (Customer Relationship Management) is software or a strategy to manage interactions with customers, improve relationships, and increase sales.\n\nReference: https://www.salesforce.com/crm/"
  },
  "what is digital marketing": {
    "answer": "Digital marketing is the promotion of products or services using digital channels like social media, search engines, email, and websites.\n\nReference: https://mailchimp.com/marketing-glossary/digital-marketing/"
  },
  "what is a business model": {
    "answer": "A business model explains how a company creates, delivers, and captures value. Examples include subscription, freemium, marketplace, and e-commerce models.\n\nReference: https://www.strategyzer.com/business-model-canvas"
  },
  "what is roi": {
    "answer": "ROI (Return on Investment) measures profitability relative to cost. Formula: ROI = (Gain from Investment - Cost of Investment) / Cost of Investment × 100.\n\nReference: https://corporatefinanceinstitute.com/resources/accounting/return-on-investment-roi/"
  },
  "what is swot analysis": {
    "answer": "SWOT Analysis is a strategic planning tool to identify Strengths, Weaknesses, Opportunities, and Threats of a business.\n\nReference: https://www.investopedia.com/terms/s/swot.asp"
  },
  "what is kpi": {
    "answer": "KPI (Key Performance Indicator) is a measurable value that shows how effectively a company achieves its objectives. Example: Sales growth, customer retention rate.\n\nReference: https://www.klipfolio.com/resources/articles/what-is-a-key-performance-indicator"
  },
  "what is supply chain management": {
    "answer": "Supply Chain Management (SCM) is managing the flow of goods, services, and information from raw materials to final customers.\n\nReference: https://www.sap.com/insights/what-is-supply-chain-management.html"
  },
  "what is startup": {
    "answer": "A startup is a young company founded to develop a unique product or service, often aiming for innovation and rapid growth.\n\nReference: https://www.forbes.com/advisor/business/what-is-a-startup/"
  },
  "print hello world program in python": {
    "answer": "Code:\n```python\nprint('Hello, World!')\n```\nOutput:\nHello, World!\n\nReference: https://www.w3schools.com/python/ref_func_print.asp"
  },
  "write a program to check if a number is prime": {
    "answer": "Code:\n```python\ndef is_prime(n):\n    if n < 2:\n        return False\n    for i in range(2, int(n ** 0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\nprint(is_prime(7))\n```\nOutput:\nTrue\n\nReference: https://www.programiz.com/python-programming/examples/prime-number"
  },
  "what is business development": {
    "answer": "Business development is the process of identifying growth opportunities, building partnerships, and creating strategies to increase revenue and market reach.\n\nReference: https://www.investopedia.com/terms/b/business-development.asp"
  },
  "what is swot analysis": {
    "answer": "SWOT Analysis is a strategic planning tool to identify Strengths, Weaknesses, Opportunities, and Threats of a business.\n\nReference: https://www.investopedia.com/terms/s/swot.asp"
  },
  "what is roi": {
    "answer": "ROI (Return on Investment) measures profitability relative to cost. Formula: ROI = (Gain from Investment - Cost of Investment) / Cost of Investment × 100.\n\nReference: https://corporatefinanceinstitute.com/resources/accounting/return-on-investment-roi/"
  },
  "hi": {
    "answer": "Hlw!!!"
  },
  "how are you": {
    "answer": "I'm just a bot, but I'm doing great! How about you?"
  },
  "tell me a joke": {
    "answer": "Why don’t skeletons fight each other? They don’t have the guts!"
  },
  "what is the time": {
    "answer": "I can’t see a clock, but your device should know."
  },
  "who made you": {
    "answer": "I was created by Subhankar Dey."
  }
    }
    
const normalizedText=text.toLowerCase().trim();

const botResponse = botResponses[normalizedText] || "I'm sorry, I don't understand that question !!!";
 
const bot = await Bot.create({
    text: typeof botResponse === "object" ? botResponse.answer : botResponse
})

return res.status(200).json({
    userMessage:user.text,
    botMessage:bot.text
});

} catch(error){
        console.log("error in message controller:", error);
        return res.status(500).json({error:"Internal server error"});
    }
}